version: '1'

services:
  # app:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - 9000:9000
  #   environment:
  #     - PORT=9000
  #     - DB_HOST=db
  #     - DB_USER=user
  #     - DB_PASSWORD=userpassword
  #     - DB_NAME=laravelmedicinedb
  #   depends_on:
  #     - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravelmedicinedb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql-data:
